package/shadowsocks-libev: fix missing const
Fixes:
output/build/shadowsocks-libev-v3.3.6/src/netutils.c:278:28: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  278 |         char *next_dot   = strchr(label, '.');

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>